/**
 * Simplified full college names (no commas) for registration form and leaderboard API.
 * Includes NIRF 2024 top 100 engineering colleges, AKTU-affiliated, GFTIs, and others.
 */
export const COLLEGES = [
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",
  "National Institute of Technology Tiruchirappalli",
  "Indian Institute of Technology Indore",
  "Indian Institute of Technology Gandhinagar",
  "National Institute of Technology Karnataka Surathkal",
  "Indian Institute of Technology Dhanbad",
  "Vellore Institute of Technology Vellore",
  "National Institute of Technology Rourkela",
  "Indian Institute of Technology Patna",
  "Jadavpur University Kolkata",
  "Indian Institute of Technology Bhubaneswar",
  "National Institute of Technology Warangal",
  "Birla Institute of Technology and Science Pilani",
  "Indian Institute of Technology Jodhpur",
  "National Institute of Technology Durgapur",
  "Indian Institute of Technology Tirupati",
  "Indian Institute of Technology Bhilai",
  "Indian Institute of Technology Goa",
  "National Institute of Technology Calicut",
  "National Institute of Technology Kurukshetra",
  "National Institute of Technology Silchar",
  "Manipal Institute of Technology Manipal",
  "Indian Institute of Technology Palakkad",
  "Indian Institute of Technology Ropar",
  "SRM Institute of Science and Technology Chennai",
  "Amrita Vishwa Vidyapeetham Coimbatore",
  "Indian Institute of Science Bangalore",
  "National Institute of Technology Jaipur",
  "National Institute of Technology Nagpur",
  "Institute of Chemical Technology Mumbai",
  "National Institute of Technology Allahabad",
  "Birla Institute of Technology Mesra Ranchi",
  "National Institute of Technology Hamirpur",
  "National Institute of Technology Meghalaya",
  "Indian Institute of Technology Mandi",
  "Anna University Chennai",
  "National Institute of Technology Agartala",
  "National Institute of Technology Raipur",
  "Thapar Institute of Engineering and Technology Patiala",
  "National Institute of Technology Jamshedpur",
  "Shri Mata Vaishno Devi University Katra",
  "Indian Institute of Information Technology Allahabad",
  "Delhi Technological University Delhi",
  "Chennai Mathematical Institute Chennai",
  "PSG College of Technology Coimbatore",
  "College of Engineering Pune",
  "RV College of Engineering Bangalore",
  "BMS College of Engineering Bangalore",
  "PES University Bangalore",
  "Chandigarh University Mohali",
  "Mumbai University Mumbai",
  "KIET Group of Institutions Ghaziabad",
  "ABES Engineering College Ghaziabad",
  "Ajay Kumar Garg Engineering College Ghaziabad",
  "GL Bajaj Institute of Technology and Management Greater Noida",
  "JSS Academy of Technical Education Noida",
  "Galgotias College of Engineering and Technology Greater Noida",
  "Amity University Noida",
  "Shiv Nadar University Greater Noida",
  "Dhirubhai Ambani Institute of Information and Communication Technology Gandhinagar",
  "Assam University Silchar",
  "Indian Institute of Carpet Technology Bhadohi",
  "Guru Ghasidas Vishwavidyalaya Institute of Technology Bilaspur",
  "School of Engineering and Technology Mizoram University Aizawl",
  "National Institute of Foundry and Forge Technology Ranchi",
  "Sant Longowal Institute of Engineering and Technology Longowal",
  "University of Hyderabad Hyderabad",
  "Bannari Amman Institute of Technology Erode",
  "Koneru Lakshmaiah Education Foundation Guntur",
  "Sathyabama Institute of Science and Technology Chennai",
  "Kalyani Government Engineering College Kalyani",
  "Maulana Azad National Institute of Technology Bhopal",
  "Sardar Vallabhbhai National Institute of Technology Surat",
  "Coimbatore Institute of Technology Coimbatore",
  "Bharati Vidyapeeth Deemed University College of Engineering Pune",
  "Netaji Subhas University of Technology Delhi",
  "Punjab Engineering College Chandigarh",
  "Thiagarajar College of Engineering Madurai",
  "Indian Institute of Information Technology Design and Manufacturing Kancheepuram",
  "Indian Institute of Engineering Science and Technology Shibpur",
  "Karunya Institute of Technology and Sciences Coimbatore",
  "Motilal Nehru National Institute of Technology Allahabad",
  "Vel Tech Rangarajan Dr Sagunthala R&D Institute of Science and Technology Chennai",
  "Vignans Foundation for Science Technology and Research Guntur",
  "Manipal University Jaipur",
  "Sri Venkateswara University Tirupati",
  "Dayalbagh Educational Institute Agra",
  "Shanmugha Arts Science Technology and Research Academy Thanjavur",
  "Pandit Dwarka Prasad Mishra Indian Institute of Information Technology Design and Manufacturing Jabalpur",
  "Jawaharlal Nehru Technological University Hyderabad",
  "University Visvesvaraya College of Engineering Bangalore",
  "Defence Institute of Advanced Technology Pune",
  "SVKM Narsee Monjee Institute of Management Studies Mumbai",
  "National Institute of Technology Arunachal Pradesh",
  "Dr BR Ambedkar National Institute of Technology Jalandhar",
  "National Institute of Technology Manipur"
];